### ISSUE TITLE
net.fortuna.ical4j.data.ParserException

### ISSUE THREAD

**Issue by sysmat** [ical4j/ical4j-vcard#16]
using:
```
<dependency>
            <groupId>org.mnode.ical4j</groupId>
            <artifactId>ical4j-vcard</artifactId>
            <version>1.0.5</version>
        </dependency>

```
when:

`VCardBuilder(java.io.InputStream in);`

error:
```
net.fortuna.ical4j.data.ParserException
	at net.fortuna.ical4j.vcard.VCardBuilder.build(VCardBuilder.java:187)
	at net.fortuna.ical4j.vcard.VCardBuilder.build(VCardBuilder.java:134)
```

**Comment by benfortuna** [comment]
Would suggest trying v2.0.0, which has now been released.
