### ISSUE TITLE
ConcurrentModificationException when looking up factory

### ISSUE THREAD

**Issue by tommix000** [ical4j/ical4j-vcard#22]
Hello ical4j !

We are using the version 1.0.5 of ical4j-vcard.
Sometimes we encounter this Exception when looking up a factory.
`java.util.ConcurrentModificationException: null
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
        at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752)
        at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:479)
        at net.fortuna.ical4j.vcard.AbstractFactoryRegistry.getFactory(AbstractFactoryRegistry.java:29)`
     
 java.util.ServiceLoader does not seem to be thread-safe

**Comment by benfortuna** [comment]
Hi, I can't recall if I've seen this error before, but we are moving away from ServiceLoader in later versions of ical4j and ical4j-vcard. Instead we now prefer the java.util.function.Supplier interface to provide the available factories.

If possible I would recommend you try the latest 2.0.0 build for loading vCards concurrently, otherwise you may need to add some synchronization around VCardBuilder.

If you must stay with 1.x then we can see if it's possible to backport the supplier pattern.

**Comment by tommix000** [comment]
No worries, we will secure our code. We will switch to version 2.0.0 anyway when released

**Comment by benfortuna** [comment]
Closing ticket as v2.0.0 is now release. Feel free to reopen if still an issue
